# Generated by Django 4.0.4 on 2025-02-25 14:10

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_cms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(null=True, upload_to='media')),
                ('blog_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('blog_title', models.CharField(max_length=100, null=True)),
                ('blog_discription', models.CharField(max_length=600)),
                ('bloger_image', models.ImageField(null=True, upload_to='media')),
                ('bloger_name', models.CharField(max_length=20)),
                ('blogs_title_slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='blog_title', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=40)),
                ('contact', models.IntegerField(null=True)),
                ('message', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='project_cms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('title', models.CharField(max_length=100, null=True)),
                ('pdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_title', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True)),
            ],
        ),
    ]
